name: hcltm testvet

on: [push, pull_request]

jobs:
  testvet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Vet
        run: make vet
      - name: Test
        run: make test

