name: hcltm pre-release

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"

jobs:
  pre-release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Bootstrap
        run: make bootstrap
      - name: Test
        run: make test
      - name: Package
        run: make pkg-linux
      - name: Upload Linux Package
        uses: actions/upload-artifact@v2
        with:
          name: linux-pkg
          path: out/hcltm-linux-amd64.tar.gz

  pre-release-osx:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Bootstrap
        run: make bootstrap
      - name: Package
        run: make pkg-osx
      - name: Upload OSX Package
        uses: actions/upload-artifact@v2
        with:
          name: osx-pkg
          path: out/hcltm-darwin-amd64.tar.gz

  pre-release:
    runs-on: ubuntu-latest
    needs: [pre-release-linux, pre-release-osx]
    steps:
      - name: Download linux package
        uses: actions/download-artifact@v2
        with:
          name: linux-pkg
      - name: Download osx package
        uses: actions/download-artifact@v2
        with:
          name: osx-pkg
      - name: Automatic Pre-Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            hcltm-linux-amd64.tar.gz
            hcltm-darwin-amd64.tar.gz
      - name: Remove artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            linux-pkg
            osx-pkg
