name: hcltm release

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  pre-release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Bootstrap
        run: make bootstrap
      - name: Test
        run: make test
      - name: Package
        run: make pkg-linux
      - name: Upload Linux Package
        uses: actions/upload-artifact@v2
        with:
          name: linux-pkg
          path: out/hcltm-linux-amd64.tar.gz

  pre-release-osx:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Bootstrap
        run: make bootstrap
      - name: Package
        run: make pkg-osx
      - name: Upload OSX Package
        uses: actions/upload-artifact@v2
        with:
          name: osx-pkg
          path: out/hcltm-darwin-amd64.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [pre-release-linux, pre-release-osx]
    steps:
      - name: Download linux package
        uses: actions/download-artifact@v2
        with:
          name: linux-pkg
      - name: Download osx package
        uses: actions/download-artifact@v2
        with:
          name: osx-pkg
      - name: Automatic Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Release"
          files: |
            hcltm-linux-amd64.tar.gz
            hcltm-darwin-amd64.tar.gz
      - name: Remove artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            linux-pkg
            osx-pkg

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [release]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
